name: EscapeLag
main: com.mcml.space.core.EscapeLag
version: Build-tester
softdepend: [ProtocolLib, AntiAttack, Essentials, RPG Items, RPGItems]
author: Vlvxingze
authors: [IzzelAliz, Sotr]
website: "https://github.com/Vlvxingze/EscapeLag"
database: false

commands:
  el:
    description: EscapeLag
    usage: "/el help"
