name: ${project.name}
main: com.mcml.space.core.EscapeLag
version: ${project.version}-b%BUILD_NUMBER%
softdepend: [ProtocolLib, AntiAttack, Essentials, RPG_Items, RPGItems]
author: Vlvxingze
api-version: 1.13
authors: [IzzelAliz, Sotr]
website: "https://github.com/Vlvxingze/EscapeLag"
description: ${project.description}
database: false

commands:
  el:
    description: EscapeLag
    usage: "/el help"
  op:
    description: OP/DEOP Command Fixed
    usage: "/el help"
  deop:
    description: OP/DEOP Command Fixed
    usage: "/el help"