version: 2
jobs:
  build:
    working_directory: ~/GelandiAssociation/EscapeLag
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run: git config --global user.email "circle@circleci.com"
    - run: git config --global user.name "CircleCI"
    - run: chmod +x scripts/build.sh
    - run: ./scripts/build.sh