version: 2
jobs:
  build:
    - run: git config --global user.email "circle@circleci.com"
    - run: git config --global user.name "CircleCI"
    - run: chmod +x scripts/build.sh
    - run: ./scripts/build.sh
    - run: yes|mv -f ./target/EscapeLag-*.jar $CIRCLE_ARTIFACTS/EscapeLag-$CIRCLE_BUILD_NUM.jar